### ISSUE TITLE
Nested object types for compiled types

### ISSUE THREAD

**Issue by calvinl** [grantila/suretype#5]
When I have a schema with a nested object, the nested object does not compile down to a basic type:

Example:
```typescript 
const PersonSchema = suretype(
  { name: 'Person' },
  v.object({
    name: annotate({ title: 'The name' }, v.string().required()),
    properties: v.object({
      age: v.number()  
    })
  })
);

type IPerson = TypeOf<typeof PersonSchema>;
```

This gets compiled to:

```typescript
type IPerson = {
    name: string;
    properties?: FlattenObject<ExtractObject<{
        age: NumberValidator<number>;
    }>, "age"> | undefined;
}
```

But I would expect it to show:

```typescript
type IPerson = {
    name: string;
    properties?: {
        age?: number;
    }
}
```

**Comment by grantila** [comment]
Those are type-wise equal, although the first is surely a bit ugly. This is a TypeScript detail which I have no control over; when it simplifies/expands a type, and when it leaves it like this.
If you're using VSCode and you hover over `IPerson`, try pressing Cmd (if you're on Mac), that sometimes triggers types to be expanded.

I'm currently working on conversion to/from suretype in [typeconv](https://github.com/grantila/typeconv) so that you can export the type to a separate file, prettified (with JSDoc comments). This would add a necessary conversion step after having changed the validator schemas, but is particularly nice if you want to export this type to users of your code/library/service. I hope to have this finished in the coming days.

**Comment by grantila** [comment]
I'm closing this now, as typeconv has support for exporting suretype schemas into (e.g.) TypeScript interfaces, as;

`typeconv -f st -t ts -o outdir 'src/validators/**/*.ts'`

similar to exporting to JSON Schemas:

`typeconv -f st -t jsc -o outdir 'src/validators/**/*.ts'`
